name: CI

on:
  push:
    branches: [ main, efish_v1.02 ]
  pull_request:
    branches: [ main, efish_v1.02 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Run Linter
      run: |
        source .venv/bin/activate
        flake8 app tests
    - name: Run Tests
      run: |
        source .venv/bin/activate
        pytest --cov=app tests/
    - name: Upload Coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml